debug: true

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cs544
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
      idleTimeout: 60000
      maxLifetime: 180000
      leakDetectionThreshold: 25000
      connectionTimeout: 2000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    template:
      routing-key: user.routingkey
      exchange: user.exchange

security:
  jwt:
    secret:
      4vzfsjym7t9lu

logging:
  level:
    org.springframework.security: debug

service-urls:
  account-manager-url: http://localhost:8082/api/
  clientManagerUrl: http://localhost:8083/api/v1/